### ISSUE TITLE
Feature to add retry count as an externalized configuration parameter

### ISSUE THREAD

**Issue by shripadnalgirkar** [seedstack/feign-addon#7]
Currently, there is not provision to customize the retry logic in this plugin.
It takes the Default retryer of Feign and the default count is 5, which is too high.

**Comment by smoneuse** [comment]
Done in the "issue-7" branch.
Retry standard parameters (period / max period / maw attempts ) can be set for a specifi endpoint and globally.
Also added feign's retryer support.

Documntation updated.

**Comment by adrienlauer** [comment]
Merged #8 which implements this enhancement. Will be released in the upcoming days.
